version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python main.py
    environment:
      - FILE_PATH=/path/to/orders.csv

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python -m unittest discover tests

