import pandas as pd
import os
import sys
from data_processing import process_data

def read_csv_file(file_path):
    if not os.path.isfile(file_path):
        print(f"Error: The file '{file_path}' does not exist.")
        sys.exit(1)
    try:
        df = pd.read_csv(file_path)
        return df
    except Exception as e:
        print(f"Error reading the CSV file: {e}")
        sys.exit(1)

def compute_metrics(df):
    try:
        # Compute the total revenue generated by the online store for each month
        monthly_revenue = df.groupby('year_month')['product_price'].sum()
        print("Total revenue generated by the online store for each month:")
        print(monthly_revenue)

        # Compute the total revenue generated by each product
        product_revenue = df.groupby('product_name')['product_price'].sum()
        print("Total revenue generated by each product:")
        print(product_revenue)

        # Compute the total revenue generated by each customer
        customer_revenue = df.groupby('customer_id')['product_price'].sum()
        print("Total revenue generated by each customer:")
        print(customer_revenue)

        # Identify the top 10 customers by revenue generated
        top_customers = customer_revenue.sort_values(ascending=False).head(10)
        print("Top 10 customers by revenue generated:")
        print(top_customers)

    except Exception as e:
        print(f"Error computing metrics: {e}")
        sys.exit(1)

def main():
    file_path = os.getenv('/path/to/orders.csv', 'orders.csv')
    df = read_csv_file(file_path)
    df = process_data(df)
    compute_metrics(df)
if __name__ == "__main__":
    main()
